services:
  - type: web
    name: kptconnect-backend
    runtime: ruby
    plan: free
    buildCommand: |
      bundle install
      bundle exec rails db:migrate
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: kptconnect-db
          property: connectionString
      - key: RAILS_ENV
        value: production
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: RAILS_SKIP_ASSET_COMPILATION
        value: "true" 

databases:
  - name: kptconnect-db
    plan: free
